MODEL:
  NAME: gspn_tiny
  DROP_PATH_RATE: 0.2
  GSPN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 7, 2 ]
    D_STATE: 8
    ITEMS_EACH_CHUNK: 2
    RATIO: 1.5
    CONV: 7
    CONV_BIAS: false
    MLP_RATIO: 4.0
    ACT_LAYER: "silu"
    FORWARDTYPE: "v1" 
    SPECIFIC_GLAYERS: [2,3]
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"